# Reset Postgres dB

Removes all tables from local Postgres

In [1]:
import pandas as pd
import uuid
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:postgres@localhost/postgres')

In [3]:
stmt_factory = """select 'drop table ' || tablename || ' cascade' as STMT
from pg_tables
where schemaname = 'public'"""
stmts = pd.read_sql(stmt_factory, engine)
stmts

                                               stmt
0      drop table buying_influence_coverage cascade
1                 drop table attribute_type cascade
2                   drop table address_type cascade
3     drop table buying_influence_role_type cascade
4        drop table buying_influence_degree cascade
5          drop table buying_influence_mode cascade
6       drop table degree_of_influence_type cascade
7                            drop table org cascade
8                           drop table role cascade
9             drop table oauth_client_token cascade
10              drop table buying_influence cascade
11                 drop table industry_type cascade
12            drop table oauth_access_token cascade
13                   drop table opportunity cascade
14                      drop table org_user cascade
15           drop table oauth_refresh_token cascade
16          drop table oauth_client_details cascade
17       drop table position_vs_competition cascade
18                       drop table address cascade
19                    drop table oauth_code cascade
20                drop table schema_version cascade
21              drop table competition_type cascade
22                  drop table country_type cascade
23                    drop table competitor cascade
24                       drop table contact cascade
25               drop table oauth_approvals cascade
26                     drop table mode_type cascade
27              drop table object_attribute cascade
28               drop table forgot_password cascade
29                       drop table account cascade
30                     drop table bluesheet cascade
31          drop table funnel_position_type cascade
32  drop table position_vs_competition_type cascade
33                   drop table competition cascade

In [12]:
conn = engine.connect()
for ds in stmts['stmt'].tolist():
    print(conn.execute(ds))

<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67f60>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>
<sqlalchemy.engine.result.ResultProxy object at 0x109b67710>